### ISSUE TITLE
Exception AttributeError: "'NoneType' object has no attribute 'GEOSSTRtree_destroy'" in <bound method STRtree.__del__ of <shapely.strtree.STRtree instance at 0x0A56A328>> ignored

### ISSUE THREAD

**Issue by fnavas00** [inkstitch/inkstitch#578]
Im getting some random error when using ink/stitch on fill shapes.. sometimes it works sometimes it doesnt but i keep getting this error on my most recent design.. I orginally use Ink/Stitch on MacOS but I updated Mojave to Catalina not knowing they stopped supporting 32 bit apps Ink/Stitch works on the inkscape 1.0 beta but since its still in beta i am unable to save PES files on my mac

Currently, im using Windows 10 with inkscape 0.92 but keep getting error messages. I either get the error message "Shape is invalid. This may happen when border overlaps" on regular shapes created with the inkscape shape tool..  Or i get this new error message

"Exception AttributeError: "'NoneType' object has no attribute 'GEOSSTRtree_destroy'" in <bound method STRtree.__del__ of <shapely.strtree.STRtree instance at 0x0A56A328>> ignored

Edit: i've been able to isolate the error on my design.. it seems that it only happens if I select multiple fill shapes but if I select each piece individually it works fine.. but at the same time if I open up a brand new document, create a circle with no stroke just fill, convert it to path and try to go to params i will get said error messages..

**Comment by lexelby** [comment]
Thanks!  We've seen this error a couple of times.  Most recently, @danielkschneider mentioned it in #573.

I've seen it too and I thought I fixed it, but I guess not. :(  I'll do more research and see if I can come up with another fix.

**Comment by fnavas00** [comment]
I've noticed that the error message ""Exception AttributeError: "'NoneType' object has no attribute 'GEOSSTRtree_destroy'" in <bound method STRtree.del of <shapely.strtree.STRtree instance at 0x0A56A328>> ignored" happens mostly whenever I prompt the params dialog without applying the parameters (I do this to preview satin column simulation to make sure the column is done correctly) It doesn't always cause the error message but the more I prompt the params dialog like this, the more likely I am to get the error message. It can be fixed by importing the object into a new file.

**Comment by lexelby** [comment]
I think the Shapely folks have been working on fixing this.  I've seen several change log entries mentioning this error.  Hopefully next time we upgrade Shapely, it will be fixed.  I don't think there's anything Ink/Stitch can do about this error.

**Comment by lexelby** [comment]
Gonna close this since I think we fixed it.  Please open a new one if it comes back though.
