### ISSUE TITLE
fill stitch: AttributeError: 'Point' object has no attribute 'geoms'

### ISSUE THREAD

**Issue by Meltanguy** [inkstitch/inkstitch#2296]
Ink/Stitch experienced an unexpected error. This means it is a bug in Ink/Stitch.

If you'd like to help please
- copy the entire error message below
- save your SVG file and
- create a new issue at https://github.com/inkstitch/inkstitch/issues

Include the error description and also (if possible) the svg file.

Ink/Stitch Version: v2.2.0 (osx)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex/base.py", line 231, in run
  File "lib/extensions/output.py", line 56, in effect
  File "lib/extensions/base.py", line 200, in elements_to_stitch_groups
  File "lib/elements/element.py", line 329, in embroider
  File "lib/elements/element.py", line 387, in validate
  File "lib/elements/fill_stitch.py", line 321, in validation_errors
  File "lib/elements/fill_stitch.py", line 274, in shape
AttributeError: 'Point' object has no attribute 'geoms'[

**Comment by bianchifan** [comment]
Have a closer look at your svg, the object "polygon" isn't shown. Delete it or make it unvisible and you will get your PES..

[238618218-261fb050-9912-4b05-879e-5a9cbb14b654.zip](https://github.com/inkstitch/inkstitch/files/11501292/238618218-261fb050-9912-4b05-879e-5a9cbb14b654.zip)

**Comment by kaalleen** [comment]
I somehow missed this one. Is this an error we still see in v3.0.1?
I cannot find the original svg file is it still available somewhere ?!

**Comment by kaalleen** [comment]
Same as #2292
Seems to be fixed...

**Comment by bianchifan** [comment]
Just tested, it works in 3.0.1

**Comment by kaalleen** [comment]
@bianchifan thanks for testing :)

Since you are here... You tried to explain a feature request for satin columns on the user meeting, but I had no time to listen. Would you mind to post in on GitHub?

**Comment by bianchifan** [comment]
CORRECTION:
The issue was opened by danielkschneider:
[#2352 Ripple stitch -short stitches](https://github.com/inkstitch/inkstitch/issues/2352)
