### ISSUE TITLE
Unable to install Inkstitch extension

### ISSUE THREAD

**Issue by tatalaulau** [inkstitch/inkstitch#4394]
Good afternoon,

I struggle to use the latest version of inkstitch 3.2.2. After installing without any problem the version, whenever I try to use Inkstitch, I get this message : 

dyld: Symbol not found: _iconv
  Referenced from: /usr/lib/libarchive.2.dylib
  Expected in: /Applications/Inkscape.app/Contents/Resources/lib/libiconv.2.dylib
 in /usr/lib/libarchive.2.dylib

My Mac version is Catalina 10.15.8 , Processor 2,7 GHz Intel Core i5 quatre cœurs

Inkscape version is 1.4.4

Can you please help me?

Thank you.

Laura

**Comment by Marif91** [comment]
et tu obtiens ce résulat avec la version 3.2.2 !

**Comment by tatalaulau** [comment]
Exactement, j'ai modifié!

**Comment by kaalleen** [comment]
Can you downgrade Inkscape (not Ink/Stitch) to version 1.4.2 and if that's not working to 1.3.2 ?
It'd be interesting to know which one worked for you, especially 1.4.2.

**Comment by tatalaulau** [comment]
I am going to check how to do so. Is there a site where I can download an older version?

**Comment by tatalaulau** [comment]
Oh it definitely works with Inkscape 1.4.2 !! Thank you!

**Comment by kaalleen** [comment]
Great, thanks for the feedback!!
