### PR TITLE
bug fixes

### LINKED ISSUE #362: Params doesn't properly handle default black fill
I am getting an error when clicking on Parameter only when the object is black. When I fill it with another color I get an error. 
screenshot 2018-12-08 19 56 31

### LINKED ISSUE #363: embroidery file import can produce paths with empty "d" attribute
Getting this lately, importing .dst and export/params/simulate gives this error.
path6248: error: Object path6248 has an empty 'd' attribute.  Please delete this object from your document.

Might be something to do with original program?

### LINKED ISSUE #377: trims not working in .JEF files
Described in https://github.com/inkstitch/inkstitch/issues/374#issuecomment-452788483, it seems that TRIM commands aren't working in JEF files.  The same design saved to DST on the same machine trims properly.

### LINKED ISSUE #386: NetworkXPointlessConcept: ('Connectivity is undefined ', 'for the null graph.')
Hi! 
I'm trying to make a patch and made it in small steps, but after inserting bitmap (and tracing it into a path), I get the following message:
NetworkXPointlessConcept: ('Connectivity is undefined ', 'for the null graph.')
What do I have to change to make this work?
Sunny

### LINKED ISSUE #387: corrupted JEF and DST output with "save as" in non-US locale
Described in detail in #364.  See the chart in https://github.com/inkstitch/inkstitch/pull/364#issuecomment-457930350 and the mention of decimal separators here: https://github.com/inkstitch/inkstitch/pull/364#issuecomment-457936088

It seems that DST and JEF files get corrupted on @jameskolme's system when using "Save As", but not when exported with "Embroider".  Changing the decimal separator from `,` to `.` (locale settings) seems to fix DST but not JEF.

### PR DESCRIPTION
**Pull request by lexelby**
fixes #362 
fixes #363 
fixes #377 
fixes #386 
fixes #387 

This fixes a couple of bugs:
  * properly handle black fill (#362)
    * for @arkopp
  * don't create paths with empty "d" attributes when importing DST, PES, etc (#363)
    * for @jameskolme
  * properly encode trims in JEF files

I also added a feature that's been bugging me for awhile: a checkbox to skip the last stitch in each row in fill stitch.  Most commercial embroidery software does this by default (probably just due to its duplicate stitch filter?).  In most cases you don't need the extra stitch at the end of each row, and Ink/Stitch was wasting stitches, which wastes time.  @wwderw you might like this one.

### CODE REVIEW

**Comment by lexelby** [comment]
@jameskolme Okay, the JEF fix is in this branch now.  As soon as it's done building you can install this and give it a go: https://github.com/inkstitch/inkstitch/releases/tag/dev-build-lexelby-bugs

**Comment by jameskolme** [comment]
Something is definitely broken now, can't access any commands, every time something similar happens. 

```
[13552] Failed to execute script inkstitch

Traceback (most recent call last):

  File "inkstitch.py", line 8, in <module>

    # ink/stitch

  File "C:\Python\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 396, in load_module

  File "lib\extensions\__init__.py", line 2, in <module>

  File "C:\Python\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 396, in load_module

  File "lib\extensions\convert_to_satin.py", line 4, in <module>

  File "C:\Python\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 396, in load_module

  File "site-packages\numpy\__init__.py", line 140, in <module>

ImportError: cannot import name _distributor_init
```

```

[4200] Failed to execute script inkstitch

Traceback (most recent call last):

  File "inkstitch.py", line 8, in <module>

    # ink/stitch

  File "C:\Python\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 396, in load_module

  File "lib\extensions\__init__.py", line 2, in <module>

  File "C:\Python\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 396, in load_module

  File "lib\extensions\convert_to_satin.py", line 4, in <module>

  File "C:\Python\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 396, in load_module

  File "site-packages\numpy\__init__.py", line 140, in <module>

ImportError: cannot import name _distributor_init
```

**Comment by lexelby** [comment]
Weird, I've never seen that before.  Maybe reinstall?

**Comment by jameskolme** [comment]
Re-installed and no help, can't select anything from inkstitch extension. Can't get it working on linux machine, unfortunately did not test older program version, so user variable is higher on linux. 

I get errors selecting:
Lettering
Params
Print
Satin tools
Simulate

Every time it is pretty much the same error.

**Comment by jameskolme** [comment]
Going back to 1.21.0 and can access again  everything.

**Comment by lexelby** [comment]
@jameskolme Okay, looks like the 1.16.0 release of numpy is broken in some way with pyinstaller.  No worries, I've pinned us to the earlier version that worked in 1.21.0.  Could you give the latest a try? https://github.com/inkstitch/inkstitch/releases/tag/dev-build-lexelby-bugs

**Comment by lexelby** [comment]
I don't think the JEF files produced by the new pyembroidery actually contain cut commands.  It looks to me like the machine is ignoring the 0-length jumps and only cutting if the next jump is longer than the "jump stitch cut" setting.

**Comment by jameskolme** [comment]
Now I can access again everything, but embroidery files not working, JEF is damaged, says machine and DST is not to be seen on machine at all. It is like nothing happened, since original 1.21.0, but I can see some difference after autoroute/trim. Only one trim is placed, but not sure is there still jump under satin, impossible to test.

**Comment by jameskolme** [comment]
Found bug that is corrupting my JEF and DST files. Changing windows number format to US, fixes export files, not permanent solution I hope, everything is upside down now.  

Trims work perfectly, if used attach command function. Using autoroute some havoc happens and all trims are not even executed on machine, some trims are completely misplaced. Long jump lines go trough every satin and those are sewed without any trims. 

Autoroute
autoroute
Attach command
manualcommand

**Comment by lexelby** [comment]
> Trims work perfectly, if used attach command function. 

Trim work in JEFs now?  Are you absolutely sure?  On mine it was acting like a jump.  I was only getting trims if I had the jump cutting feature turned on and the jump was long enough...

**Comment by lexelby** [comment]
> Changing windows number format to US, fixes export files, not permanent solution I hope, everything is upside down now.

Ouch, that's not good!  I'll see if I can get to the bottom of that one.  What number format / locale did you have set previously?

**Comment by lexelby** [comment]
> Using autoroute some havoc happens and all trims are not even executed on machine,

I'm wondering if this might be the thing I saw, where JEF trims were being ignored if they were under the "jump trim" setting.

I also saw a vague mention on a forum that Janome machines ignore trim commands in JEF files if they are less than the "jump trim" setting but that may be incorrect.


> some trims are completely misplaced.

Misplaced how?  What I see in your pictures makes sense, although the stitch path that Auto-Route has chosen is a bit odd.  See my next answer for details.

> Long jump lines go trough every satin and those are sewed without any trims.

Those long jump lines are running stitch that auto-route uses to create its stitching path.  I think I see what happened in your picture: it created running stitch for the first two satins, sewed the third, and then sewed the first two, right?  A little strange, but you _do_ end up with what you asked for: all three satins are sewn and have trim commands.

The reason you get a weird stitch plan is because by default, Auto-Route chooses a starting and ending position automatically.  You can change the starting and ending position by assigning "Auto-Route Satin Starting Point" and ending point command to  satins in your set.  It will use the endpoint of the little line connecting the command symbol to the satin, so you can just move those to the right spot.

If you don't use those commands, then Auto-Route will decide for itself where to start and end.  Sometimes it doesn't do a very good job of it.  It will pick the left-most point on the left-most satin as the start, and the right-most point on the right-most satin as the end.  That makes a lot of sense for a line of text.  It doesn't make much sense at all for a set of three satins stacked vertically.

**Comment by jameskolme** [comment]
> Trim work in JEFs now? Are you absolutely sure? On mine it was acting like a jump. I was only getting trims if I had the jump cutting feature turned on and the jump was long enough...

No, I can't repeat, actually I can't get any program to work on machine with trim on it currently. Changing number format might be blind luck, but it worked when I first tested. Number format is europe, arabic numerals with decimal comma. 

Here is one example with bad JEF output
[trim.zip](https://github.com/inkstitch/inkstitch/files/2786697/trim.zip)

> I also saw a vague mention on a forum that Janome machines ignore trim commands in JEF files if they are less than the "jump trim" setting but that may be incorrect.

Must be incorrect, otherwise trim command would be completely useless. It might be the case if auto trim is enabled, so it would skip programmed trims, this is only guess. This is one thing that might be nice to test. 

Janome embroidery editor make trims, but it uses JEF+ format. 

> Misplaced how? 

I have programs here to try, auto route don't end where it would be expected to end and trims not trimming that much. 
[cut_2.zip](https://github.com/inkstitch/inkstitch/files/2786873/cut_2.zip)

**Comment by jameskolme** [comment]
@lexelby I was wrong about number format, sorry about that. 

Problem that I can repeat, is export issue, no error messages.

If exporting using save copy, JEF and DTS files fail every time. But if I use embroider to save, files might work. Using Janome embroidery editor to test files, sometimes it will refuse to open because embroidery is bigger than hoop, not sure what is standard size, but it can be defined to pretty big. Happily this is one step forward, example files for bad and good files. 
[rinkulaooppeeli save copy.zip](https://github.com/inkstitch/inkstitch/files/2792574/rinkulaooppeeli.save.copy.zip)

Now with working workaround to export, I can try to trim again something.

**Comment by jameskolme** [comment]
Still can make programs that work, I can't understand how I did first programs that trims, can't repeat that. 

Made this program to test programmed trims using attach command, but nothing happens.
notrim
This should trigger trim over or under 3mm no matter what. This is done simply using stroke from single line. 

Second attempt similar trim, but this time using two paths on every satin, can't get working program out, machine rejects embroider and save as export. 

Third attempt, this time just in case, changed number format to US again, otherwise same as previous.
Working program again using embroidery export, but save as is broken.  So changing number formats does something, but nothing that makes trims work.  
 
Can repeat all of this and no trim.

**Comment by lexelby** [comment]
Alright, let's ignore trims for a moment.

This problem where "save as" gives you broken files, but "embroider" files work... when did this start?  Do earlier versions of Ink/Stitch have the problem?

I'm having a hard time understanding what your workflow is, so I can't understand what's going on here.  This may sound weird, but if you could create a screen recording showing me the steps you're taking, I would really appreciate it.

**Comment by lexelby** [comment]
Thank you, that video is incredibly useful!  I'll see if I can reproduce the problem.

**Comment by jameskolme** [comment]
Done some poking and results:
inkstitch

I wonder why save as DST suddenly worked twice 1.18.0 and 1.17.0

**Comment by lexelby** [comment]
Wow, nice chart!  What happens if you do "save as" without having any objects selected?

**Comment by jameskolme** [comment]
No difference, end result is bad.

**Comment by jameskolme** [comment]
Both rejects. Just tested using another computer, but results are same.

**Comment by lexelby** [comment]
Alright, thanks.  I'm baffled, but it's clear from your chart that this branch is not responsible for the problem, so I'll open a separate issue.

**Comment by wwderw** [comment]
I've gone back to 1.20 and I've not noticed any issues with DST files going through Save As, which I do most of the time and only use embroider when I'm wanting the stitch plan.

I'll have to go back through  and take a closer look to make sure.

**Comment by jameskolme** [comment]
I think this is what is happening: 
https://en.wikipedia.org/wiki/Decimal_separator

Switching numbers to US again and my DST export save as works, JEF is still broken.

**Comment by lexelby** [comment]
It's a great theory, but I haven't yet figured out where in the code the number format might be a problem.  I also don't understand why changing your number format only fixes DST and not JEF, or why you're only having trouble with "save as".  Still trying to figure all that out.

**Comment by jameskolme** [comment]
Discovered new feature. Not sure if this is any help but, there is situation when JEF save as works. I get lazy and made only one satin along path, single line. This works, making anything else than single line and save as stop working.  

I was messing with Inkscape language setting, but I think that's not it.

**Comment by lexelby** [comment]
Okay!  I think this one for real fixes .JEF trims.  Testing would be appreciated.

**Comment by jameskolme** [comment]
I'm not sure how to download this?

**Comment by lexelby** [comment]
Oh sorry!  For every pull request, Travis builds ink/stitch and posts it on the releases page, like this: https://github.com/inkstitch/inkstitch/releases/tag/dev-build-lexelby-bugs

The release is named after the branch name at the top of the pull request page.  In this case that's `lexelby/bugs`.

**Comment by jameskolme** [comment]
Ok thanks, I feel like noob now.  Because it reads  lexelby released this on Dec 12, 2018, so I was assuming it was old, but next line: built on 2019-02-10 01:48:04 GMT. I'll get mi coat :)

This is what comes out from save as, but embroider works just fine. 
filenotsaving

After quick test with trim, works really well using auto route or attach commands.

**Comment by lexelby** [comment]
Yeah, that's confusing, isn't it? :( It sets the date of the release when it's first posted, but not updating it when Travis uploads new zips.  That's why I have the "built on" date there.  Sorry for the confusion!

Wow, just "could not be saved"?  Does it give you any kind of error message from Python?  If not I really have no idea why it's failing...

**Comment by jameskolme** [comment]
No extra errors and this is very constant with every inkstitch export  format. If exporting to G-code extra message pops up with: file ends with newline! windows messed with it? But this still gives same error message and will not save. Using zip option only PES file shows on archive and winrar says archive is damaged.  

Embroider export seems to work just fine.

**Comment by lexelby** [comment]
Oh!  Silly me, that's the debug stuff I put in to debug the carriage return issue.  Now that I know it's happening, I'll remove that error message and see if I can get rid of the carriage return.

**Comment by lexelby** [comment]
Okay, fixed the issue with the stray newline at the end of the file when you use "save as".  That should fix the corruption issue (#387).  I think that means we now have working JEF trims and files that should load properly even in Janome's preview software.  Could you give it a go?

**Comment by lexelby** [comment]
Those last two commits fix #386.  I really should merge this thing and make a new release soon, this PR is getting huge :)

**Comment by jameskolme** [comment]
Yes, export works, someone has been very busy :)
